### ISSUE TITLE
Import 3D dataset with hyperspy_swift_library

### ISSUE THREAD

**Issue by ltizei** [hyperspy/hyperspy_swift_library#1]
I am trying to import a nion swift library which contains two 2D images and one 3D data set (EELS spectrum image). The images are loaded but not the  spectrum image. I can provide the library by email if necessary.

**Comment by francisco-dlp** [comment]
Thanks @ltizei for reporting the issue. Please do share the library to help identify the issue.

**Comment by ltizei** [comment]
I should have closed this before. it was a problem with my dataset.
